# Generated by Django 2.0.5 on 2018-06-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20180612_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='scraping.NewsItem')),
            ],
        ),
    ]
