# Generated by Django 2.0.5 on 2018-06-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_tagnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='kotaLowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('perusahaan', models.CharField(max_length=200, null=True)),
                ('tanggalDaftar', models.DateTimeField()),
                ('tanggalTutup', models.DateTimeField()),
                ('bidang', models.CharField(max_length=100, null=True)),
                ('gaji', models.CharField(max_length=150, null=True)),
                ('deskripsi', models.TextField()),
                ('syarat', models.TextField()),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kotalowongan',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='scraping.Lowongan'),
        ),
    ]
