# Generated by Django 2.0.5 on 2018-06-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20180627_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kotaLowongan',
            new_name='KotaLowongans',
        ),
    ]
