# Generated by Django 2.0.5 on 2018-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20180627_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='syarat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='tanggalDaftar',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='tanggalTutup',
            field=models.DateTimeField(null=True),
        ),
    ]
