# Generated by Django 2.0.5 on 2018-06-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20180628_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(max_length=100, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='scraping.Lowongan')),
            ],
        ),
        migrations.RemoveField(
            model_name='kotalowongan',
            name='url',
        ),
        migrations.DeleteModel(
            name='KotaLowongan',
        ),
    ]
