# Generated by Django 2.0.5 on 2018-06-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20180628_0139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kota',
            new_name='KotaLowongan',
        ),
    ]
