# Generated by Django 2.0.5 on 2018-06-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_auto_20180628_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotalowongan',
            name='url',
        ),
        migrations.DeleteModel(
            name='KotaLowongan',
        ),
        migrations.DeleteModel(
            name='Lowonganku',
        ),
    ]
