# Generated by Django 2.0.5 on 2018-06-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_auto_20180628_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='KotaLowonganku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lowonganku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('perusahaan', models.CharField(max_length=200, null=True)),
                ('tanggalDaftar', models.DateTimeField(null=True)),
                ('tanggalTutup', models.DateTimeField(null=True)),
                ('bidang', models.CharField(max_length=100, null=True)),
                ('gaji', models.CharField(max_length=150, null=True)),
                ('deskripsi', models.TextField(null=True)),
                ('syarat', models.TextField(null=True)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kotalowonganku',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='scraping.Lowonganku'),
        ),
    ]
