# Generated by Django 2.0.5 on 2018-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_auto_20180628_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowonganku',
            name='jumlahPelamar',
            field=models.IntegerField(null=True),
        ),
    ]
