# Generated by Django 2.0.5 on 2018-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detikNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('breadcrumbs', models.TextField()),
                ('tanggal', models.TextField()),
                ('penulis', models.TextField()),
                ('judul', models.TextField()),
                ('berita', models.TextField()),
                ('tag', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
