# Generated by Django 2.0.5 on 2018-06-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_detiknewsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detiknewsitem',
            name='unique_id',
        ),
    ]
