# Generated by Django 2.0.5 on 2018-06-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_detiknewsitem_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detiknewsitem',
            name='website',
            field=models.TextField(default='detik'),
            preserve_default=False,
        ),
    ]
