# Generated by Django 2.0.5 on 2018-06-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180608_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumbs', models.CharField(max_length=150, null=True)),
                ('penulis', models.CharField(max_length=100, null=True)),
                ('judul', models.CharField(max_length=200, null=True)),
                ('berita', models.TextField()),
                ('tag', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='detikNewsItem',
        ),
    ]
