# Generated by Django 2.0.5 on 2018-05-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag01',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag02',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag03',
        ),
    ]
